package goqrsvg

import (
	"bytes"
	"os"
	"testing"

	"github.com/ajstarks/svgo/float"
	"github.com/boombuler/barcode/qr"
)

func Test_goqrsvg(t *testing.T) {
	buf := bytes.NewBufferString("")
	s := svg.New(buf)

	// Create the barcode
	qrCode, _ := qr.Encode("Hello World", qr.M, qr.Auto)

	// Write QR code to SVG
	qs := NewQrSVG(qrCode, 5.0)
	qs.StartQrSVG(s)
	qs.WriteQrSVG(s)

	s.End()

	// Check if output the same as correctOutput
	if buf.String() != correctOutput {
		t.Error("Something is not right... The SVG created is not the same as correctOutput.")
	}
}

func ExampleNewQrSVG() {
	s := svg.New(os.Stdout)

	// Create the barcode
	qrCode, _ := qr.Encode("Hello World", qr.M, qr.Auto)

	// Write QR code to SVG
	qs := NewQrSVG(qrCode, 5)
	qs.StartQrSVG(s)
	qs.WriteQrSVG(s)

	s.End()
}

const correctOutput = `<?xml version="1.0"?>
<!-- Generated by SVGo (float) -->
<svg width="145.00" height="145.00"
     xmlns="http://www.w3.org/2000/svg"
     xmlns:xlink="http://www.w3.org/1999/xlink">
<rect x="20.00" y="20.00" width="5.00" height="5.00" />
<rect x="25.00" y="20.00" width="5.00" height="5.00" />
<rect x="30.00" y="20.00" width="5.00" height="5.00" />
<rect x="35.00" y="20.00" width="5.00" height="5.00" />
<rect x="40.00" y="20.00" width="5.00" height="5.00" />
<rect x="45.00" y="20.00" width="5.00" height="5.00" />
<rect x="50.00" y="20.00" width="5.00" height="5.00" />
<rect x="70.00" y="20.00" width="5.00" height="5.00" />
<rect x="80.00" y="20.00" width="5.00" height="5.00" />
<rect x="90.00" y="20.00" width="5.00" height="5.00" />
<rect x="95.00" y="20.00" width="5.00" height="5.00" />
<rect x="100.00" y="20.00" width="5.00" height="5.00" />
<rect x="105.00" y="20.00" width="5.00" height="5.00" />
<rect x="110.00" y="20.00" width="5.00" height="5.00" />
<rect x="115.00" y="20.00" width="5.00" height="5.00" />
<rect x="120.00" y="20.00" width="5.00" height="5.00" />
<rect x="20.00" y="25.00" width="5.00" height="5.00" />
<rect x="50.00" y="25.00" width="5.00" height="5.00" />
<rect x="70.00" y="25.00" width="5.00" height="5.00" />
<rect x="80.00" y="25.00" width="5.00" height="5.00" />
<rect x="90.00" y="25.00" width="5.00" height="5.00" />
<rect x="120.00" y="25.00" width="5.00" height="5.00" />
<rect x="20.00" y="30.00" width="5.00" height="5.00" />
<rect x="30.00" y="30.00" width="5.00" height="5.00" />
<rect x="35.00" y="30.00" width="5.00" height="5.00" />
<rect x="40.00" y="30.00" width="5.00" height="5.00" />
<rect x="50.00" y="30.00" width="5.00" height="5.00" />
<rect x="60.00" y="30.00" width="5.00" height="5.00" />
<rect x="70.00" y="30.00" width="5.00" height="5.00" />
<rect x="80.00" y="30.00" width="5.00" height="5.00" />
<rect x="90.00" y="30.00" width="5.00" height="5.00" />
<rect x="100.00" y="30.00" width="5.00" height="5.00" />
<rect x="105.00" y="30.00" width="5.00" height="5.00" />
<rect x="110.00" y="30.00" width="5.00" height="5.00" />
<rect x="120.00" y="30.00" width="5.00" height="5.00" />
<rect x="20.00" y="35.00" width="5.00" height="5.00" />
<rect x="30.00" y="35.00" width="5.00" height="5.00" />
<rect x="35.00" y="35.00" width="5.00" height="5.00" />
<rect x="40.00" y="35.00" width="5.00" height="5.00" />
<rect x="50.00" y="35.00" width="5.00" height="5.00" />
<rect x="60.00" y="35.00" width="5.00" height="5.00" />
<rect x="65.00" y="35.00" width="5.00" height="5.00" />
<rect x="75.00" y="35.00" width="5.00" height="5.00" />
<rect x="80.00" y="35.00" width="5.00" height="5.00" />
<rect x="90.00" y="35.00" width="5.00" height="5.00" />
<rect x="100.00" y="35.00" width="5.00" height="5.00" />
<rect x="105.00" y="35.00" width="5.00" height="5.00" />
<rect x="110.00" y="35.00" width="5.00" height="5.00" />
<rect x="120.00" y="35.00" width="5.00" height="5.00" />
<rect x="20.00" y="40.00" width="5.00" height="5.00" />
<rect x="30.00" y="40.00" width="5.00" height="5.00" />
<rect x="35.00" y="40.00" width="5.00" height="5.00" />
<rect x="40.00" y="40.00" width="5.00" height="5.00" />
<rect x="50.00" y="40.00" width="5.00" height="5.00" />
<rect x="60.00" y="40.00" width="5.00" height="5.00" />
<rect x="80.00" y="40.00" width="5.00" height="5.00" />
<rect x="90.00" y="40.00" width="5.00" height="5.00" />
<rect x="100.00" y="40.00" width="5.00" height="5.00" />
<rect x="105.00" y="40.00" width="5.00" height="5.00" />
<rect x="110.00" y="40.00" width="5.00" height="5.00" />
<rect x="120.00" y="40.00" width="5.00" height="5.00" />
<rect x="20.00" y="45.00" width="5.00" height="5.00" />
<rect x="50.00" y="45.00" width="5.00" height="5.00" />
<rect x="60.00" y="45.00" width="5.00" height="5.00" />
<rect x="70.00" y="45.00" width="5.00" height="5.00" />
<rect x="75.00" y="45.00" width="5.00" height="5.00" />
<rect x="90.00" y="45.00" width="5.00" height="5.00" />
<rect x="120.00" y="45.00" width="5.00" height="5.00" />
<rect x="20.00" y="50.00" width="5.00" height="5.00" />
<rect x="25.00" y="50.00" width="5.00" height="5.00" />
<rect x="30.00" y="50.00" width="5.00" height="5.00" />
<rect x="35.00" y="50.00" width="5.00" height="5.00" />
<rect x="40.00" y="50.00" width="5.00" height="5.00" />
<rect x="45.00" y="50.00" width="5.00" height="5.00" />
<rect x="50.00" y="50.00" width="5.00" height="5.00" />
<rect x="60.00" y="50.00" width="5.00" height="5.00" />
<rect x="70.00" y="50.00" width="5.00" height="5.00" />
<rect x="80.00" y="50.00" width="5.00" height="5.00" />
<rect x="90.00" y="50.00" width="5.00" height="5.00" />
<rect x="95.00" y="50.00" width="5.00" height="5.00" />
<rect x="100.00" y="50.00" width="5.00" height="5.00" />
<rect x="105.00" y="50.00" width="5.00" height="5.00" />
<rect x="110.00" y="50.00" width="5.00" height="5.00" />
<rect x="115.00" y="50.00" width="5.00" height="5.00" />
<rect x="120.00" y="50.00" width="5.00" height="5.00" />
<rect x="60.00" y="55.00" width="5.00" height="5.00" />
<rect x="65.00" y="55.00" width="5.00" height="5.00" />
<rect x="20.00" y="60.00" width="5.00" height="5.00" />
<rect x="30.00" y="60.00" width="5.00" height="5.00" />
<rect x="35.00" y="60.00" width="5.00" height="5.00" />
<rect x="40.00" y="60.00" width="5.00" height="5.00" />
<rect x="45.00" y="60.00" width="5.00" height="5.00" />
<rect x="50.00" y="60.00" width="5.00" height="5.00" />
<rect x="75.00" y="60.00" width="5.00" height="5.00" />
<rect x="90.00" y="60.00" width="5.00" height="5.00" />
<rect x="95.00" y="60.00" width="5.00" height="5.00" />
<rect x="100.00" y="60.00" width="5.00" height="5.00" />
<rect x="105.00" y="60.00" width="5.00" height="5.00" />
<rect x="110.00" y="60.00" width="5.00" height="5.00" />
<rect x="20.00" y="65.00" width="5.00" height="5.00" />
<rect x="35.00" y="65.00" width="5.00" height="5.00" />
<rect x="40.00" y="65.00" width="5.00" height="5.00" />
<rect x="45.00" y="65.00" width="5.00" height="5.00" />
<rect x="60.00" y="65.00" width="5.00" height="5.00" />
<rect x="75.00" y="65.00" width="5.00" height="5.00" />
<rect x="80.00" y="65.00" width="5.00" height="5.00" />
<rect x="85.00" y="65.00" width="5.00" height="5.00" />
<rect x="90.00" y="65.00" width="5.00" height="5.00" />
<rect x="95.00" y="65.00" width="5.00" height="5.00" />
<rect x="100.00" y="65.00" width="5.00" height="5.00" />
<rect x="105.00" y="65.00" width="5.00" height="5.00" />
<rect x="110.00" y="65.00" width="5.00" height="5.00" />
<rect x="120.00" y="65.00" width="5.00" height="5.00" />
<rect x="25.00" y="70.00" width="5.00" height="5.00" />
<rect x="30.00" y="70.00" width="5.00" height="5.00" />
<rect x="35.00" y="70.00" width="5.00" height="5.00" />
<rect x="40.00" y="70.00" width="5.00" height="5.00" />
<rect x="50.00" y="70.00" width="5.00" height="5.00" />
<rect x="55.00" y="70.00" width="5.00" height="5.00" />
<rect x="65.00" y="70.00" width="5.00" height="5.00" />
<rect x="80.00" y="70.00" width="5.00" height="5.00" />
<rect x="85.00" y="70.00" width="5.00" height="5.00" />
<rect x="90.00" y="70.00" width="5.00" height="5.00" />
<rect x="105.00" y="70.00" width="5.00" height="5.00" />
<rect x="110.00" y="70.00" width="5.00" height="5.00" />
<rect x="115.00" y="70.00" width="5.00" height="5.00" />
<rect x="20.00" y="75.00" width="5.00" height="5.00" />
<rect x="30.00" y="75.00" width="5.00" height="5.00" />
<rect x="40.00" y="75.00" width="5.00" height="5.00" />
<rect x="60.00" y="75.00" width="5.00" height="5.00" />
<rect x="65.00" y="75.00" width="5.00" height="5.00" />
<rect x="75.00" y="75.00" width="5.00" height="5.00" />
<rect x="80.00" y="75.00" width="5.00" height="5.00" />
<rect x="85.00" y="75.00" width="5.00" height="5.00" />
<rect x="100.00" y="75.00" width="5.00" height="5.00" />
<rect x="105.00" y="75.00" width="5.00" height="5.00" />
<rect x="110.00" y="75.00" width="5.00" height="5.00" />
<rect x="25.00" y="80.00" width="5.00" height="5.00" />
<rect x="30.00" y="80.00" width="5.00" height="5.00" />
<rect x="50.00" y="80.00" width="5.00" height="5.00" />
<rect x="80.00" y="80.00" width="5.00" height="5.00" />
<rect x="85.00" y="80.00" width="5.00" height="5.00" />
<rect x="90.00" y="80.00" width="5.00" height="5.00" />
<rect x="120.00" y="80.00" width="5.00" height="5.00" />
<rect x="60.00" y="85.00" width="5.00" height="5.00" />
<rect x="70.00" y="85.00" width="5.00" height="5.00" />
<rect x="80.00" y="85.00" width="5.00" height="5.00" />
<rect x="105.00" y="85.00" width="5.00" height="5.00" />
<rect x="20.00" y="90.00" width="5.00" height="5.00" />
<rect x="25.00" y="90.00" width="5.00" height="5.00" />
<rect x="30.00" y="90.00" width="5.00" height="5.00" />
<rect x="35.00" y="90.00" width="5.00" height="5.00" />
<rect x="40.00" y="90.00" width="5.00" height="5.00" />
<rect x="45.00" y="90.00" width="5.00" height="5.00" />
<rect x="50.00" y="90.00" width="5.00" height="5.00" />
<rect x="75.00" y="90.00" width="5.00" height="5.00" />
<rect x="90.00" y="90.00" width="5.00" height="5.00" />
<rect x="110.00" y="90.00" width="5.00" height="5.00" />
<rect x="115.00" y="90.00" width="5.00" height="5.00" />
<rect x="20.00" y="95.00" width="5.00" height="5.00" />
<rect x="50.00" y="95.00" width="5.00" height="5.00" />
<rect x="60.00" y="95.00" width="5.00" height="5.00" />
<rect x="85.00" y="95.00" width="5.00" height="5.00" />
<rect x="95.00" y="95.00" width="5.00" height="5.00" />
<rect x="105.00" y="95.00" width="5.00" height="5.00" />
<rect x="110.00" y="95.00" width="5.00" height="5.00" />
<rect x="115.00" y="95.00" width="5.00" height="5.00" />
<rect x="120.00" y="95.00" width="5.00" height="5.00" />
<rect x="20.00" y="100.00" width="5.00" height="5.00" />
<rect x="30.00" y="100.00" width="5.00" height="5.00" />
<rect x="35.00" y="100.00" width="5.00" height="5.00" />
<rect x="40.00" y="100.00" width="5.00" height="5.00" />
<rect x="50.00" y="100.00" width="5.00" height="5.00" />
<rect x="60.00" y="100.00" width="5.00" height="5.00" />
<rect x="75.00" y="100.00" width="5.00" height="5.00" />
<rect x="90.00" y="100.00" width="5.00" height="5.00" />
<rect x="95.00" y="100.00" width="5.00" height="5.00" />
<rect x="120.00" y="100.00" width="5.00" height="5.00" />
<rect x="20.00" y="105.00" width="5.00" height="5.00" />
<rect x="30.00" y="105.00" width="5.00" height="5.00" />
<rect x="35.00" y="105.00" width="5.00" height="5.00" />
<rect x="40.00" y="105.00" width="5.00" height="5.00" />
<rect x="50.00" y="105.00" width="5.00" height="5.00" />
<rect x="60.00" y="105.00" width="5.00" height="5.00" />
<rect x="65.00" y="105.00" width="5.00" height="5.00" />
<rect x="70.00" y="105.00" width="5.00" height="5.00" />
<rect x="80.00" y="105.00" width="5.00" height="5.00" />
<rect x="85.00" y="105.00" width="5.00" height="5.00" />
<rect x="90.00" y="105.00" width="5.00" height="5.00" />
<rect x="95.00" y="105.00" width="5.00" height="5.00" />
<rect x="100.00" y="105.00" width="5.00" height="5.00" />
<rect x="105.00" y="105.00" width="5.00" height="5.00" />
<rect x="20.00" y="110.00" width="5.00" height="5.00" />
<rect x="30.00" y="110.00" width="5.00" height="5.00" />
<rect x="35.00" y="110.00" width="5.00" height="5.00" />
<rect x="40.00" y="110.00" width="5.00" height="5.00" />
<rect x="50.00" y="110.00" width="5.00" height="5.00" />
<rect x="60.00" y="110.00" width="5.00" height="5.00" />
<rect x="65.00" y="110.00" width="5.00" height="5.00" />
<rect x="80.00" y="110.00" width="5.00" height="5.00" />
<rect x="95.00" y="110.00" width="5.00" height="5.00" />
<rect x="110.00" y="110.00" width="5.00" height="5.00" />
<rect x="20.00" y="115.00" width="5.00" height="5.00" />
<rect x="50.00" y="115.00" width="5.00" height="5.00" />
<rect x="70.00" y="115.00" width="5.00" height="5.00" />
<rect x="80.00" y="115.00" width="5.00" height="5.00" />
<rect x="85.00" y="115.00" width="5.00" height="5.00" />
<rect x="100.00" y="115.00" width="5.00" height="5.00" />
<rect x="105.00" y="115.00" width="5.00" height="5.00" />
<rect x="110.00" y="115.00" width="5.00" height="5.00" />
<rect x="20.00" y="120.00" width="5.00" height="5.00" />
<rect x="25.00" y="120.00" width="5.00" height="5.00" />
<rect x="30.00" y="120.00" width="5.00" height="5.00" />
<rect x="35.00" y="120.00" width="5.00" height="5.00" />
<rect x="40.00" y="120.00" width="5.00" height="5.00" />
<rect x="45.00" y="120.00" width="5.00" height="5.00" />
<rect x="50.00" y="120.00" width="5.00" height="5.00" />
<rect x="60.00" y="120.00" width="5.00" height="5.00" />
<rect x="70.00" y="120.00" width="5.00" height="5.00" />
<rect x="75.00" y="120.00" width="5.00" height="5.00" />
<rect x="80.00" y="120.00" width="5.00" height="5.00" />
<rect x="90.00" y="120.00" width="5.00" height="5.00" />
<rect x="100.00" y="120.00" width="5.00" height="5.00" />
<rect x="115.00" y="120.00" width="5.00" height="5.00" />
</svg>
`
